<a href="https://colab.research.google.com/github/Mochismo/LearnPython/blob/main/Twelfth_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/train.csv')
df.shape
df

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 81 columns]


# Problem 2
1.   The dataset includes 79 variables that are used to determine the cost of
     houses in Iowa city. The variables include information that looks at the
     surrounding environment for example paved drives, the land properties for
     example slope, and finally information on the house itself for example
     kitchen space. All these information are used to determine the cost of the
     houses. Some spaces dont have information. Some are important while others 
     look same all through therefore can be ignored.

In [20]:
#Problem 3(a)
t = df.info(verbose=True) # information of all colums
#print(t)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

We have a total of 38 variants as numerical and 43 variants as text data.

In [21]:
# Problem 3(b)
s = df.iloc[:,80] #row location
print(s)

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

The target variable this time is the sale price.

In [22]:
# Problem 3(c)
v = df.describe() # mean, sd,and quartiles info.
print(v)

                Id   MSSubClass  ...       YrSold      SalePrice
count  1460.000000  1460.000000  ...  1460.000000    1460.000000
mean    730.500000    56.897260  ...  2007.815753  180921.195890
std     421.610009    42.300571  ...     1.328095   79442.502883
min       1.000000    20.000000  ...  2006.000000   34900.000000
25%     365.750000    20.000000  ...  2007.000000  129975.000000
50%     730.500000    50.000000  ...  2008.000000  163000.000000
75%    1095.250000    70.000000  ...  2009.000000  214000.000000
max    1460.000000   190.000000  ...  2010.000000  755000.000000

[8 rows x 38 columns]

In [25]:
# Problem 4(a)
Total = df.count()
Total
missing_ratio = df.isna().mean()*100
missing_ratio
Final = pd.concat([Total, missing_ratio], axis=1, keys=['Total', 'missing_ratio'] )
Final

               Total  missing_ratio
Id              1460       0.000000
MSSubClass      1460       0.000000
MSZoning        1460       0.000000
LotFrontage     1201      17.739726
LotArea         1460       0.000000
...              ...            ...
MoSold          1460       0.000000
YrSold          1460       0.000000
SaleType        1460       0.000000
SaleCondition   1460       0.000000
SalePrice       1460       0.000000

[81 rows x 2 columns]

In [ ]:
#Problem 4(b)
perc = 0.3425
min_count =  int(((100-perc)/100)*df.shape[0] + 1)
mod_df = df.dropna( axis=1, 
                thresh=min_count)
print(mod_df)

In [ ]:
# Problem 4(c)
perc = 7.9365
min_count =  int(((100-perc)/100)*mod_df.shape[0] + 1)
mod_df2 = mod_df.dropna( axis=0, 
                thresh=min_count)
print(mod_df2)

# Problem 5
1.   Skewness is a measure of symmetry, or more precisely, the lack of
     symmetry. A distribution, or data set, is symmetric if it looks the same
     to the left and right of the center point.
2.   Kurtosis is a measure of whether the data are heavy-tailed or light-tailed
     relative to a normal distribution. That is, data sets with high kurtosis
     tend to have heavy tails, or outliers. Data sets with low kurtosis tend to
     have light tails, or lack of outliers.

In [ ]:
# Problem 6(a)
import seaborn as sns
sns.displot(data=df, x="SalePrice", kde=True)

In [ ]:
# Problem 6(b)
sns.histplot(data=df, x="SalePrice")

In [ ]:
# Problem 6(c)
Skew = df['SalePrice'].astype(float).skew() 
Kurtosis = df['SalePrice'].astype(float).kurt()
print(Skew)
print(Kurtosis)

In [ ]:
# Problem 6(d)
import numpy as np
#df['log_SalePrice']=np.log1p(df.SalePrice)

In [ ]:
# Problem 6(d)
import matplotlib.pyplot as plt
plt.figure(figsize=(5,7))
plt.hist(np.log1p(df.SalePrice), bins=100)
plt.xlabel("Sale Price")
plt.title("Histogram of Sale Price")
plt.show()

In [ ]:
# Problem 6(e)
Skew = np.log1p(df.SalePrice).astype(float).skew() 
Kurtosis = np.log1p(df.SalePrice).astype(float).kurt()
print(Skew)
print(Kurtosis)

The Kurtosis and Skew values increase showing that there is a reduced tail density after the logarithmic transformation.Before we could see lack of symmetry and a denser tail towards the right. The logarithmic transormation here has helped reduce outliers greatly as evident in the big value change of 'kurtosis'.

In [ ]:
# Problem 7(a)
corr = df.corr()
fig, ax =plt.subplots(figsize=(25,22))
sns.heatmap(corr, annot=True, ax=ax, cmap='coolwarm')
plt.title('Heat Map')

In [ ]:
# Problem 7(b)
def corrFilter(x: pd.DataFrame, bound: float):
    xCorr = x.corr()
    xFiltered = xCorr[((xCorr >= bound) | (xCorr <= -bound)) & (xCorr !=1.000)]
    xFlattened = xFiltered.unstack().sort_values().drop_duplicates()
    return xFlattened

corrFilter(df, .641)

In [ ]:
# Problem 7(c)
dfCorr = df.corr()
filteredDf = dfCorr[((dfCorr >= .641) | (dfCorr <= -.641)) & (dfCorr !=1.000)]
plt.figure(figsize=(30,10))
sns.heatmap(filteredDf, annot=True, cmap="Reds")
plt.show()



1.   The overal quality and general living area have a high correlation to the
     sale price. TotRmsAbvGrd and general living area have a high correlation
     too. This shows the variants are related in a way and can be used to
     determine the house cost which is our target.
2.   Garrage areas and garrage cars have a high correlation cofficient

In [ ]:
# Problem 7(e)
def corrFilter(x: pd.DataFrame, bound: float):
    xCorr = x.corr()
    xFiltered = xCorr[((xCorr >= bound) | (xCorr <= -bound)) & (xCorr !=1.000)]
    xFlattened = xFiltered.unstack().sort_values().drop_duplicates()
    return xFlattened

corrFilter(df, .82)

In [ ]:
# Problem 7(f)
dfCorr = df.corr()
filteredDf = dfCorr[((dfCorr >= .82) | (dfCorr <= -.82)) & (dfCorr !=1.000)]
plt.figure(figsize=(30,10))
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
sns.set_style('white')
sns.heatmap(filteredDf, annot=True, cmap="Reds", annot_kws={'size':16})
plt.show()

The relationship between two variables is generally considered strong when their r value is larger than 0.7. The correlation r measures the strength of the linear relationship between two quantitative variables.